version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4
jobs:
  build:
    docker:
      - image: circleci/golang:1.12.7
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: go get -v -t -d ./...
      - run:
          name: Create build
          command: go build
      - run:
          name: Create data directory
          command: |
            mkdir /var/lib/sprawl
            chmod 755 /var/lib/sprawl
      - run:
          name: Run tests
          command: go test -coverprofile=coverage.txt -covermode=atomic -v ./...
      - codecov/upload:
          file: ./coverage.txt
